=== TimRD/efrei_web_services/TP/TP_XML_2/cd.dtd
<!-- DTD created at Tue Nov 20 16:52:41 CET 2018 with EditiX. Please insert an encoding attribute header for converting any DTD  -->

<!ELEMENT CDlist ((CD)+)>
<!ELEMENT CD (composer, (performance)+,publisher, (length)?)>
<!ELEMENT performance (composition, (soloist)?,(orchestra, conductor)?)>

<!ELEMENT composer (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT composition (#PCDATA)>
<!ELEMENT soloist (#PCDATA)>
<!ELEMENT orchestra (#PCDATA)>
<!ELEMENT conductor (#PCDATA)>

=== TimRD/efrei_web_services/TP/TP_XML_2/cd.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New document created with EditiX at Tue Nov 20 17:58:29 CET 2018 -->



<!DOCTYPE CDlist SYSTEM "cd.dtd">
<CDlist>
	<CD>
		<composer></composer>
		<performance>
			<composition></composition>
			<soloist></soloist>
			<orchestra>London Symphony</orchestra>
			<conductor></conductor>
		</performance>
		<publisher>Deutsche</publisher>
	</CD>
</CDlist>
